<a href="https://colab.research.google.com/github/bhavya1239/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy


In [ ]:
import numpy as np
y=[1,2,3,4]
print(y)


[1, 2, 3, 4]


In [ ]:
#tell the execution time of single line
#for list
%timeit [j**4 for j in range(1,9)]


2.5 µs ± 54 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#tell the execution time of single line
#for array
#arange function - creates an array from starting point to end point
import numpy as np

%timeit np.arange(1,9)**4

2.36 µs ± 48.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#Array
import numpy as np

x=[1,2,3,4]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [ ]:
l=[]
for i in range(1,5):
  int_1 = int(input("Enter: "))
  l.append(int_1)
print(np.array(l))

Enter: 14
Enter: 15
Enter: 15
Enter: 45
[14 15 15 45]


In [ ]:
#2-D Array
#No. of data should be same
ar2= np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
ar3= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [ ]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
#ZEROS NUMPY
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [ ]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#ONES
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [ ]:
#EMPTY
#print previous data
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [ ]:
#RANGE
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
#DIAGONAL
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
##LINESPACE
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [ ]:
#RANDOM
#rand()
#values btw 0 to 1
var = np.random.rand(4)
print(var)

[0.4280732  0.30262732 0.10767408 0.85641464]


In [ ]:
var1 = np.random.rand(2,5)
print(var1)

[[0.3830293  0.05015699 0.01690797 0.91233849 0.76797304]
 [0.64037806 0.00990656 0.67330845 0.07068033 0.41343508]]


In [ ]:
#RANDN()
var2 = np.random.randn(4)
print(var2)

[-1.60767123  0.28836626 -1.61126431 -1.01678427]


In [ ]:
var3 = np.random.randn(2,5)
print(var3)

[[-0.17879578 -0.24721461  0.98240757 -1.68879895 -0.62617818]
 [ 0.19124523 -1.98820183  0.1879668   0.59014765 -1.13441141]]


In [ ]:
#RANF()
var4 = np.random.ranf(5)
print(var4)

[0.99227389 0.92012456 0.68002897 0.97315691 0.34933144]


In [ ]:
#RANDINT()
#var5 = np.random.randint(min,max,total_values)
var5 = np.random.randint(5,20,5)
print(var5)

[17 11 10 10 17]


In [ ]:
#DATATYPE


var = np.array([1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  int64


In [ ]:
var = np.array([1.5,2.5,3.5,4.5])
print("Data Type: ",var.dtype)

Data Type:  float64


In [ ]:
var = np.array(["A","B","C"])
print("Data Type: ",var.dtype)


Data Type:  <U1


In [ ]:
var = np.array([1,2,3,4,"A"])
print("Data Type: ",var.dtype)

Data Type:  <U21


In [ ]:
#conversion
q = np.array([1,2,3,4],dtype = np.int8)
print("Data Type",q.dtype)
print(q)

Data Type int8
[1 2 3 4]


In [ ]:
#shortcut
q1 = np.array([1,2,3,4],dtype = "f")
print("Data Type",q1.dtype)
print(q1)

Data Type float32
[1. 2. 3. 4.]


In [ ]:
q2 = np.array([1,2,3,4])
new = np.float32(q2)
print("Data Type",q2.dtype)
print("Data Type",new.dtype)
print(q2)
print(new)

Data Type int64
Data Type float32
[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
q2 = np.array([1,2,3,4])
new = np.float32(q2)

new1 = np.int_(new
               )
print("Data Type",q2.dtype)
print("Data Type",new.dtype)
print("Data Type",new1.dtype)
print(q2)
print(new)
print(new1)

Data Type int64
Data Type float32
Data Type int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
w2 = np.array([1,2,3,4])

new11 = w2.astype(float)
print(w2)
print(new11)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
#ARITHMATIC OPERATION

In [ ]:
#add
s = np.array([1,2,3,4])
sadd = s + 3
print(sadd)

[4 5 6 7]


In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
sadd = s + d
print(sadd)

[2 4 6 8]


In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
sadd = np.add(s,d)
print(sadd)

[2 4 6 8]


In [ ]:
#SUBTRACT

In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
ssub = s - d
print(ssub)

[0 0 0 0]


In [ ]:
#MULTIPLY

In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
smulti = s * d
print(smulti)

[ 1  4  9 16]


In [ ]:
#DIVIDE

In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
sdiv = s / d
print(sdiv)

[1. 1. 1. 1.]


In [ ]:
#MOD

In [ ]:
s = np.array([1,2,3,4])
d = np.array([1,2,3,4])
smod = s % d
print(smod)

[0 0 0 0]


In [ ]:
#2D ARRAY

In [ ]:
g = np.array([1,2,3,4],[1,2,3,4])
f = np.array([1,2,3,4],[1,2,3,4])
sadd2 = g + f
print(sadd2)

TypeError: ignored

In [ ]:
g = np.array([1,2,3,4],[1,2,3,4])
f = np.array([1,2,3,4],[1,2,3,4])
print(g)
print()
print(f)
print()
sadd2 = g + f
print(sadd2)

TypeError: ignored

In [ ]:
#ARITHMATIC FUNCTION

In [ ]:
np = np.array([1,2,3,4,5,2,3])
print("min: ",np.min(np),np.argrmin(np))
print("max: ",np.max(np),np,argmax(np))

TypeError: ignored

In [ ]:
sd = np.array([1,2,3,4,5],[4,8,7,5,5])
print(np.min(sd,axis=1)) #row

TypeError: ignored

In [ ]:
sd1 = np.array([1,2,3,4,5],[4,8,7,5,5])
print(np.min(sd1,axis=0)) #col


AttributeError: ignored

In [ ]:
as = np.array([1,2,3,4,5,2,3])
print("min: ",np.min(as),np.agrmin(as))
print("max: ",np.max(as),np,argmax(as))
print("sqrt: ",np.sqrt(as))

SyntaxError: ignored

In [ ]:
ff = np.array([1,2,3])
print(np.sin(ff))
print(np.cos(ff))
print(np.cumsum(ff))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


In [ ]:
#SHAPE

In [ ]:
import numpy as np
cv = np.array([[1,2],[1,2]])
print(cv)
print()
print(cv.shape)

[[1 2]
 [1 2]]

(2, 2)


In [ ]:
cx = np.array([2,2,3,5], ndmin=4)
print(cx)
print(cx.ndim)
print()
print(cx.shape)

[[[[2 2 3 5]]]]
4

(1, 1, 1, 4)


In [ ]:
#RESHAPE

In [ ]:
nj = np.array([1,2,3,4,5,6])
print(nj)
print(nj.ndim)

print()

g = nj.reshape(3,2)
print(g)
print(g.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
nj2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(nj2)
print(nj2.ndim)

print()

g2 = nj2.reshape(2,3,2)

print(g2)
print(g2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
nj2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(nj2)
print(nj2.ndim)

print()

g2 = nj2.reshape(2,3,2)

print(g2)
print(g2.ndim)

print()

one = g2.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [ ]:
#BROADCASTING

In [ ]:
#error due to shape diff
ss = np.array([1,2,3,4])

dd = np.array([1,2,3])

print( ss + dd)

ValueError: ignored

In [ ]:
ss1 = np.array([1,2,3,4])

dd1 = np.array([1,2,3,4])

print( ss1 + dd1)

[2 4 6 8]


In [ ]:
ss2 = np.array([1,2,3,4])
print(ss2.shape)

dd2 = np.array([[1],[2],[3]])
print(dd2.shape)
print()
print(ss2)
print()
print(dd2)
print()
print( ss2 + dd2)

(4,)
(3, 1)

[1 2 3 4]

[[1]
 [2]
 [3]]

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [ ]:
#INDEXING

In [ ]:
import numpy as np
zx = np.array([5,8,9,7])
#              0,1,2,3
#            -4,-3,-2,-1
print(zx[1])
print(zx[-2])

8
9


In [ ]:
ww = np.array([[9,7,8],[5,8,7]])

print(ww)
print(ww.ndim)
print()
print(ww[0,2])


[[9 7 8]
 [5 8 7]]
2

8


In [ ]:
ww1 = np.array([[[9,7],[5,7]]])

print(ww1)
print()
print(ww1.ndim)
print()
print(ww1[0,1,1])


[[[9 7]
  [5 7]]]

3

7


In [ ]:
#SLICING

In [ ]:
import numpy as np
ee = np.array([1,2,3,4,5,6,7])
#              0,1,2,3,4,5,6
print(ee)
print("2 to 5 : ",ee[1:5])
print()
print("2 to end:",ee[1:])
print()
print("start to 5: ",ee[:5])
print()
print("stop :",ee[::2])
print()
print("stop: ", ee[1:6:2])
print()

[1 2 3 4 5 6 7]
2 to 5 :  [2 3 4 5]

2 to end: [2 3 4 5 6 7]

start to 5:  [1 2 3 4 5]

stop : [1 3 5 7]

stop:  [2 4 6]



In [ ]:
tt = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(tt)
print()
print("8 to 5 :",tt[1,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

8 to 5 : [6 7 8]


In [ ]:
#COPY VS VIEW

In [ ]:
import numpy as np
vv = np.array([1,2,3,4])
co = vv.copy()

print("var:",vv)
print("Copy:",co)

var: [1 2 3 4]
Copy: [1 2 3 4]


In [ ]:
v = np.array([1,2,3,4])
vi = v.view()

print("v:",v)
print("view:",vi)

v: [1 2 3 4]
view: [1 2 3 4]


In [ ]:
#JOIN AND SPLIT

In [ ]:
import numpy as np

cat = np.array([1,2,3,4])
cat2 = np.array([5,6,7,8])

ar = np.concatenate((cat,cat2))
print(ar)

[1 2 3 4 5 6 7 8]


In [ ]:
from numpy.core.multiarray import concatenate
sui = np.array([[1,2],[4,5]])
sui1 = np.array([[5,4],[5,8]])

ar_sui = np.concatenate((sui,sui1),axis=0)
print(sui)
print()
print(sui1)
print()
print(ar_sui)

[[1 2]
 [4 5]]

[[5 4]
 [5 8]]

[[1 2]
 [4 5]
 [5 4]
 [5 8]]


In [ ]:
ni = np.array([1,2,3,4])
nii = np.array([5,6,7,8])
a_ni = np.stack((ni,nii),axis = 1)
print(a_ni)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
niii = np.array([1,2,3,4])
niiii = np.array([5,6,7,8])
a_niii = np.stack((niii,niiii),axis = 1)
a_niii1 = np.hstack((niii,niiii)) #row
a_niii2 = np.vstack((niii,niiii)) #col
a_niii3 = np.dstack((niii,niiii)) #height
print(a_niii)
print()
print(a_niii1)
print()
print(a_niii2)
print()
print(a_niii3)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [ ]:
#SPLIT

In [ ]:
import numpy as np
df = np.array([1,2,3,4,5,6,7,8,9,10])

print(df)

a1 = np.array_split(df,3)

print()
print(a1)
print(a1[0])
print(type(a1))

[ 1  2  3  4  5  6  7  8  9 10]

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[1 2 3 4]
<class 'list'>


In [ ]:
df1 = np.array([[1,2,3,4],[5,6,7,8,9,10]])

print(df1)

a11 = np.array_split(df1,3)

print()
print(a11)
print()
print(a11[0])
print()
print(type(a11))
print()

[list([1, 2, 3, 4]) list([5, 6, 7, 8, 9, 10])]

[array([list([1, 2, 3, 4])], dtype=object), array([list([5, 6, 7, 8, 9, 10])], dtype=object), array([], dtype=object)]

[list([1, 2, 3, 4])]

<class 'list'>



<ipython-input-111-f0b24be86c99>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  df1 = np.array([[1,2,3,4],[5,6,7,8,9,10]])


In [ ]:
#SEARCH

In [ ]:
import numpy as np
bn = np.array([1,2,3,4,5,6,2,8,2,10])

cx = np.where( bn == 2)

print(cx)

(array([1, 6, 8]),)
